import type { Bloco } from "@/types/diagnostico";

const baseSubitens = [
  {
    letra: "a" as const,
    funcao: "Âncora ampla",
    texto: "Defina o compromisso inicial sem revelar o que está sendo testado.",
    ehComprometedora: false,
  },
  {
    letra: "b" as const,
    funcao: "Especificidade disfarçada",
    texto: "Apresente um detalhe natural sem usar termos técnicos.",
    ehComprometedora: false,
  },
  {
    letra: "c" as const,
    funcao: "Pergunta de processo",
    texto: "Pergunte como, quem, quando ou de que forma algo foi realizado.",
    ehComprometedora: false,
  },
  {
    letra: "d" as const,
    funcao: "Cruzamento interno",
    texto: "Peça confirmação de um detalhe que veio do subitem anterior.",
    ehComprometedora: false,
  },
  {
    letra: "e" as const,
    funcao: "Evidência documental",
    texto: "Solicite um elemento específico que comprove a prática.",
    ehComprometedora: false,
  },
  {
    letra: "f" as const,
    funcao: "Aplicação real",
    texto: "Pergunte como a prática se aplica de fato na rotina da empresa.",
    ehComprometedora: false,
  },
  {
    letra: "g" as const,
    funcao: "Pergunta comprometedora",
    texto: "Se um Auditor Fiscal do Trabalho chegar agora, a empresa está pronta sem ajustes?",
    ehComprometedora: true,
  },
];

export const blocos: Bloco[] = [
  {
    numero: 1,
    tema: "Documentação e Evidências",
    peso: 0.2,
    critico: true,
    itens: [
      {
        id: "1.1",
        bloco: 1,
        titulo: "Inventário documental",
        perguntaPrincipal: "O inventário de documentos fiscais e trabalhistas está completo e atualizado?",
        subitens: baseSubitens,
      },
      {
        id: "1.2",
        bloco: 1,
        titulo: "Registro de treinamentos",
        perguntaPrincipal: "Os treinamentos obrigatórios estão registrados e disponíveis?",
        subitens: baseSubitens,
      },
      {
        id: "1.3",
        bloco: 1,
        titulo: "Processos documentados",
        perguntaPrincipal: "Os processos de controle interno estão documentados e foram aplicados?",
        subitens: baseSubitens,
      },
      {
        id: "1.4",
        bloco: 1,
        titulo: "Controle de evidências",
        perguntaPrincipal: "As evidências de conformidade são organizadas e fáceis de acessar?",
        subitens: baseSubitens,
      },
      {
        id: "1.5",
        bloco: 1,
        titulo: "Auditorias internas",
        perguntaPrincipal: "A empresa realiza auditorias internas e mantém relatórios atualizados?",
        subitens: baseSubitens,
      },
    ],
  },
  {
    numero: 2,
    tema: "Riscos Psicossociais e Organização do Trabalho",
    peso: 0.2,
    critico: true,
    itens: [
      {
        id: "2.1",
        bloco: 2,
        titulo: "Avaliação de riscos psicossociais",
        perguntaPrincipal: "A empresa identifica formalmente os riscos psicossociais?",
        subitens: baseSubitens,
      },
      {
        id: "2.2",
        bloco: 2,
        titulo: "Metodologia aplicada",
        perguntaPrincipal: "A avaliação usa metodologia documentada e adequada?",
        subitens: baseSubitens,
      },
      {
        id: "2.3",
        bloco: 2,
        titulo: "Monitoramento de indicadores",
        perguntaPrincipal: "Há monitoramento contínuo dos sintomas e indicadores psicossociais?",
        subitens: baseSubitens,
      },
      {
        id: "2.4",
        bloco: 2,
        titulo: "Ambiente de trabalho",
        perguntaPrincipal: "O ambiente de trabalho é avaliado quanto a fatores psicossociais?",
        subitens: baseSubitens,
      },
      {
        id: "2.5",
        bloco: 2,
        titulo: "Plano de controle",
        perguntaPrincipal: "Há plano de controle ou mitigação para riscos psicossociais?",
        subitens: baseSubitens,
      },
    ],
  },
  {
    numero: 3,
    tema: "Liderança e Gestão de Pessoas",
    peso: 0.15,
    critico: false,
    itens: [
      {
        id: "3.1",
        bloco: 3,
        titulo: "Capacitação das lideranças",
        perguntaPrincipal: "As lideranças recebem formação sobre riscos psicossociais?",
        subitens: baseSubitens,
      },
      {
        id: "3.2",
        bloco: 3,
        titulo: "Gestão de desempenho",
        perguntaPrincipal: "Há critérios de desempenho alinhados à saúde mental dos trabalhadores?",
        subitens: baseSubitens,
      },
      {
        id: "3.3",
        bloco: 3,
        titulo: "Fluxo de comunicação",
        perguntaPrincipal: "A comunicação interna permite registrar demandas e incidentes?",
        subitens: baseSubitens,
      },
      {
        id: "3.4",
        bloco: 3,
        titulo: "Responsabilidades claras",
        perguntaPrincipal: "As responsabilidades sobre saúde mental estão formalmente distribuídas?",
        subitens: baseSubitens,
      },
      {
        id: "3.5",
        bloco: 3,
        titulo: "Cultura preventiva",
        perguntaPrincipal: "A liderança estimula uma cultura preventiva de riscos psicossociais?",
        subitens: baseSubitens,
      },
    ],
  },
  {
    numero: 4,
    tema: "Políticas Internas e Aplicação Real",
    peso: 0.15,
    critico: false,
    itens: [
      {
        id: "4.1",
        bloco: 4,
        titulo: "Política de saúde mental",
        perguntaPrincipal: "Existe política interna de prevenção ao estresse e assédio?",
        subitens: baseSubitens,
      },
      {
        id: "4.2",
        bloco: 4,
        titulo: "Comunicação de políticas",
        perguntaPrincipal: "As políticas internas são comunicadas aos trabalhadores?",
        subitens: baseSubitens,
      },
      {
        id: "4.3",
        bloco: 4,
        titulo: "Aplicação prática",
        perguntaPrincipal: "A empresa aplica na prática as políticas que declara?",
        subitens: baseSubitens,
      },
      {
        id: "4.4",
        bloco: 4,
        titulo: "Registro de ações",
        perguntaPrincipal: "Há registro de ações efetivas e controle do cumprimento?",
        subitens: baseSubitens,
      },
      {
        id: "4.5",
        bloco: 4,
        titulo: "Avaliação de resultados",
        perguntaPrincipal: "Os resultados das políticas internas são avaliados e atualizados?",
        subitens: baseSubitens,
      },
    ],
  },
  {
    numero: 5,
    tema: "Participação dos Trabalhadores",
    peso: 0.15,
    critico: true,
    itens: [
      {
        id: "5.1",
        bloco: 5,
        titulo: "Participação em comitês",
        perguntaPrincipal: "Os trabalhadores participam de comitês ou grupos de trabalho?",
        subitens: baseSubitens,
      },
      {
        id: "5.2",
        bloco: 5,
        titulo: "Acesso a informação",
        perguntaPrincipal: "Os trabalhadores têm acesso real ao PGR e aos relatórios?",
        subitens: baseSubitens,
      },
      {
        id: "5.3",
        bloco: 5,
        titulo: "Registro de demandas",
        perguntaPrincipal: "As demandas e sugestões dos trabalhadores são registradas?",
        subitens: baseSubitens,
      },
      {
        id: "5.4",
        bloco: 5,
        titulo: "Comunicação transparente",
        perguntaPrincipal: "A empresa comunica resultado e ações relacionadas aos trabalhadores?",
        subitens: baseSubitens,
      },
      {
        id: "5.5",
        bloco: 5,
        titulo: "Engajamento efetivo",
        perguntaPrincipal: "A participação dos trabalhadores é efetiva e não apenas formal?",
        subitens: baseSubitens,
      },
    ],
  },
  {
    numero: 6,
    tema: "Capacidade de Resposta Institucional",
    peso: 0.15,
    critico: false,
    itens: [
      {
        id: "6.1",
        bloco: 6,
        titulo: "Resposta a auditorias",
        perguntaPrincipal: "A empresa está preparada para apresentar resposta em auditoria?",
        subitens: baseSubitens,
      },
      {
        id: "6.2",
        bloco: 6,
        titulo: "Conformidade eletrônica",
        perguntaPrincipal: "Os registros eletrônicos (eSocial, etc.) são consistentes com a prática?",
        subitens: baseSubitens,
      },
      {
        id: "6.3",
        bloco: 6,
        titulo: "Gestão de incidentes",
        perguntaPrincipal: "Incidentes são registrados e tratados formalmente?",
        subitens: baseSubitens,
      },
      {
        id: "6.4",
        bloco: 6,
        titulo: "Plano de ação institucional",
        perguntaPrincipal: "Há plano formal de ação para não conformidades?",
        subitens: baseSubitens,
      },
      {
        id: "6.5",
        bloco: 6,
        titulo: "Capacidade de correção",
        perguntaPrincipal: "A empresa corrige problemas rapidamente após identificação?",
        subitens: baseSubitens,
      },
    ],
  },
];

export const niveisResposta = [
  { label: "Documentado e aplicado", value: 100 as const },
  { label: "Existe mas sem registro", value: 60 as const },
  { label: "Iniciado mas incompleto", value: 25 as const },
  { label: "Não existe", value: 0 as const },
];
